add typescript support - Message
plivo/plivo-node pull request #161
Opened 2020-08-16 14:00 UTC by huzaif-plivo

2020-09-06 12:02 UTC, ahmednaser94 commented
any updates on this pull request to be merged?

2020-09-14 14:48 UTC, anand-plivo requested changes
@ahmednaser94 most of the parameter types are set as 'any', can you please share why? 
If it is possible please check the implementation and set appropriate types.

2021-01-18 18:33 UTC, karthikdechiraju-plivo approved these changes

2021-01-19 08:00 UTC, nixonsam approved these changes

2021-01-19 08:01 UTC, merged